name: CI/CD - MkDocs Deployment to GitHub Pages
  push:
    branches: 
      - main
      # - mkdocs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ## Set the working directory dynamically
      working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name "Nhat-Thanh Nguyen"
          git config user.email nnthanh101@gmail.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Cache Dependencies
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install MkDocs and Dependencies
        run: |
          pip install --no-cache-dir mkdocs mkdocs-material mkdocstrings mkdocstrings[python]
      
      ## --- Install 'task' CLI ---
      - name: Install Taskfile CLI
        run: |
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV  ## Add Task CLI to PATH
          task --version
      
      ## --- Build and Deploy MkDocs ---
      - name: Build & Deploy Mkdocs
        run: |
          mkdocs gh-deploy --force
        working-directory: ${{env.working-directory}}
