name: CI. MkDocs to GitHub-Pages
on:
  push:
    branches: 
      - main
      # - mkdocs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # working-directory: docs
      working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name "Nhat-Thanh Nguyen"
          git config user.email nnthanh101@gmail.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs mkdocs-material mkdocstrings mkdocstrings[python]
      - name: Build & Deploy Mkdocs
        run: |
          mkdocs gh-deploy --force
        working-directory: ${{env.working-directory}}
